name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this if your main branch is named differently
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version you need

      - name: Install dependencies
        working-directory: ./fontend
        run: npm install

      - name: Build the project
        working-directory: ./fontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./fontend
          publish_dir: ./build
